### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by maxgrass**
a bug with unicode symbols during compilation with uglifying was fixed, so we need to update the requirejs

### CODE REVIEW

**Comment by wturyn** [comment]
Hi maxgrass, you've made pull request to wrong repo. This is my fork, not the original.

**Comment by maxgrass** [comment]
Actually I intended to find a newer fork, do you change the plugin in any
way except updating the dependencies?

Am Mittwoch, 4. März 2015 schrieb Wojciech Turyn :

**Comment by wturyn** [comment]
I don't, but i also i didn't intent to publish it. I needed newer dependency becasue it supports multiple config files.

**Comment by maxgrass** [comment]
no problem. Thank you!

Am Mittwoch, 4. März 2015 schrieb Wojciech Turyn :

**Pull request merged**
